### ISSUE TITLE
编译失败，退出码为：1

### ISSUE THREAD

**Issue by liangxiufeng** [fanvanzh/3dtiles#120]
我按照https://github.com/fanvanzh/3dtiles/wiki/How-to-build 所给的说明进行编译，但是在第5步执行了命令：cargo build --release --verbose后出现如下情况：
![image](https://user-images.githubusercontent.com/27732935/71609313-5650b100-2bc2-11ea-84c7-c312e8bf6055.png)
请问需要如何解决？

**Comment by fanvanzh** [comment]
请检查下 是否安装好 vs 编译环境、 git clone 的文件是否有缺失。

**Comment by liangxiufeng** [comment]
同时存在多个vs版本会影响编译么

**Comment by liangxiufeng** [comment]
> 请检查下是否安装好vs编译环境，git clone的文件是否有缺失。

如果系统中安装了多个vs版本，会影响到编译么

**Comment by liyu998** [comment]
= note: D:\git_projects\3dtiles\target\release\deps\3dtile-e3fd6dc71a31dbe7.3dtile.ari94qaz-cgu.4.rcgu.o:3dtile.ari94qaz-cg:(.text+0x3297): undefined reference to `osgb23dtile_path'
          D:\git_projects\3dtiles\target\release\deps\3dtile-e3fd6dc71a31dbe7.3dtile.ari94qaz-cgu.4.rcgu.o:3dtile.ari94qaz-cg:(.text+0x4280): undefined reference to `degree2rad'
          D:\git_projects\3dtiles\target\release\deps\3dtile-e3fd6dc71a31dbe7.3dtile.ari94qaz-cgu.4.rcgu.o:3dtile.ari94qaz-cg:(.text+0x429c): undefined reference to `degree2rad'
          D:\git_projects\3dtiles\target\release\deps\3dtile-e3fd6dc71a31dbe7.3dtile.ari94qaz-cgu.4.rcgu.o:3dtile.ari94qaz-cg:(.text+0x47e2): undefined reference to `transform_c'
          D:\git_projects\3dtiles\target\release\deps\3dtile-e3fd6dc71a31dbe7.3dtile.ari94qaz-cgu.8.rcgu.o:3dtile.ari94qaz-cg:(.text+0x3954): undefined reference to `shp23dtile'
          D:\git_projects\3dtiles\target\release\deps\3dtile-e3fd6dc71a31dbe7.3dtile.ari94qaz-cgu.9.rcgu.o:3dtile.ari94qaz-cg:(.text+0x39b3): undefined reference to `make_gltf'
          D:\git_projects\3dtiles\target\release\deps\3dtile-e3fd6dc71a31dbe7.3dtile.ari94qaz-cgu.9.rcgu.o:3dtile.ari94qaz-cg:(.text+0x40b0): undefined reference to `epsg_convert'


我得到的错误，不知道为啥调用gcc。如何检查git clone的文件有缺失呢？如何检测vc编译环境是好的呢？多谢！

**Comment by liyu998** [comment]
我安装了vc，但是为什么会调用gcc呢？

**Comment by liangxiufeng** [comment]
> 我安装了vc，但是为什么会调用gcc呢？

我也在琢磨，我这边环境应该是问题不大的，还在排查

**Comment by fanvanzh** [comment]
你看看 rust 的 toolchain 用的哪个？

执行 `rustup show` 命令，查看 rustc 配套的链接器。

**Comment by liyu998** [comment]
D:\git_projects\3dtiles>rustup show
Default host: i686-pc-windows-gnu
rustup home:  C:\Users\scxgo\.rustup

stable-i686-pc-windows-gnu (default)
rustc 1.40.0 (73528e339 2019-12-16)
本人是rust这个工具的菜鸟，请指教。

**Comment by fanvanzh** [comment]
i686-pc-windows-gnu  是 linux 编译工具链，请先安装 vs， 在安装 rustup_init.exe

**Comment by liyu998** [comment]
好的，多谢！ 我试一下。

**Comment by liyu998** [comment]
我换了编译工具，由gcc换成了vc，但是，还是出现了错误：
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x86\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LARGEADDRESSAWARE" "/SAFESEH" "/LIBPATH:C:\\Users\\scxgo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\3dtile.3dtile.5vnerurs-cgu.0.rcgu.o" "D:\\git_projects\\3dtiles\\target\\release\\deps\\3dtile.3dtile.5vnerurs-cgu.1.rcgu.o" "D:\\git_projects\\3dtiles\\target\\release\\deps\\3dtile.3dtile.5vnerurs-cgu.10.rcgu.o" "D:\\git_projects\\3dtiles\\target\\release\\deps\\3dtile.3dtile.5vnerurs-cgu.11.rcgu.o" "D:\\git_projects\\3dtiles\\target\\release\\deps\\3dtile.3dtile.5vnerurs-cgu.12.rcgu.o" "D:\\git_projects\\3dtiles\\target\\release\\deps\\3dtile.3dtile.5vnerurs-cgu.13.rcgu.o" "D:\\git_projects\\3dtiles\\target\\release\\deps\\3dtile.3dtile.5vnerurs-cgu.14.rcgu.o" "D:\\git_projects\\3dtiles\\target\\release\\deps\\3dtile.3dtile.5vnerurs-cgu.15.rcgu.o" "D:\\git_projects\\3dtiles\\target\\release\\deps\\3dtile.3dtile.5vnerurs-cgu.2.rcgu.o" "D:\\git_projects\\3dtiles\\target\\release\\deps\\3dtile.3dtile.5vnerurs-cgu.3.rcgu.o" "D:\\git_projects\\3dtiles\\target\\release\\deps\\3dtile.3dtile.5vnerurs-cgu.4.rcgu.o" "D:\\git_projects\\3dtiles\\target\\release\\deps\\3dtile.3dtile.5vnerurs-cgu.5.rcgu.o" "D:\\git_projects\\3dtiles\\target\\release\\deps\\3dtile.3dtile.5vnerurs-cgu.6.rcgu.o" "D:\\git_projects\\3dtiles\\target\\release\\deps\\3dtile.3dtile.5vnerurs-cgu.7.rcgu.o" "D:\\git_projects\\3dtiles\\target\\release\\deps\\3dtile.3dtile.5vnerurs-cgu.8.rcgu.o" "D:\\git_projects\\3dtiles\\target\\release\\deps\\3dtile.3dtile.5vnerurs-cgu.9.rcgu.o" "/OUT:D:\\git_projects\\3dtiles\\target\\release\\deps\\3dtile.exe" "D:\\git_projects\\3dtiles\\target\\release\\deps\\3dtile.fgaqbw6er7rgbuv.rcgu.o" "/OPT:REF,ICF" "/DEBUG" "/NATVIS:C:\\Users\\scxgo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\scxgo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\scxgo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/LIBPATH:D:\\git_projects\\3dtiles\\target\\release\\deps" "/LIBPATH:C:\\Users\\scxgo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\librayon-4154e51ee392c1e1.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\librayon_core-d2a7f68c88ed0a38.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libnum_cpus-4f6ee4f269c75101.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libcrossbeam_queue-092d03389db37156.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libcrossbeam_deque-e2f2f7cc0c8d4919.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libcrossbeam_epoch-9bd2eeb9e45a3b5a.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libscopeguard-e4e4a21d75c8af37.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libmemoffset-a37816714a41c38a.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libcrossbeam_utils-f3bd7522a486fc3b.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libeither-c01dccd2300dc75e.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\liblibc-a6b5a77bdf56e1b3.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libbyteorder-4be0ac7f7e10216c.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libenv_logger-39f31d4f5cda743e.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libregex-0c50c4b60f0673b7.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libthread_local-531cff5a0d1b733d.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\liblazy_static-0beed999da480775.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libregex_syntax-3dcc1280055cc077.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libaho_corasick-9ed8cbbc6836c8ba.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libmemchr-8a57bba492b42a14.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libhumantime-6d17c6527006a3f9.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libquick_error-ff28a77dc1a750af.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libtermcolor-faef3fce4bd8666b.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libwincolor-dedab0da7544bafe.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libwinapi_util-6531768ffedf44fd.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libchrono-36135e49d50fefa0.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libnum_integer-ba6e3d1d58d2ef1b.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libnum_traits-a53b24c8dde201ea.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libtime-50775091501afe55.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libserde_xml_rs-2c5f10783138b7a9.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\liblog-e33fdac9e364cb5c.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\liblog-a4bab11f20e287a8.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libcfg_if-e91d43af6b0ae434.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libxml-ed25e84f049a04a0.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libbitflags-13d48c2a3517a302.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libserde_json-649a7564ad39a8d9.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libryu-70837d9a8e05d3fb.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libitoa-77fde4cd43134e13.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libserde-7e48ba1295232262.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libclap-340b3988a812208a.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libvec_map-326f8a2d9dd18ba0.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libtextwrap-45c0fdc97de65678.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libunicode_width-40c8fe4e451c54ca.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libstrsim-3dd57102c8e1c607.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libbitflags-a298b78a48148490.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libatty-0a1de519a628626a.rlib" "D:\\git_projects\\3dtiles\\target\\release\\deps\\libwinapi-11ce9f8bd88f417f.rlib" "C:\\Users\\scxgo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libstd-a2af7cbca70405c4.rlib" "C:\\Users\\scxgo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libpanic_unwind-8f8ad41ed0b34354.rlib" "C:\\Users\\scxgo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libhashbrown-3442ca764a847dfc.rlib" "C:\\Users\\scxgo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-726244614f5a8f3a.rlib" "C:\\Users\\scxgo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libbacktrace-29b7599014a92286.rlib" "C:\\Users\\scxgo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\librustc_demangle-519f7f7caa7ec7f2.rlib" "C:\\Users\\scxgo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libunwind-feba7334127a8724.rlib" "C:\\Users\\scxgo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libcfg_if-6d75d87de5ddb74c.rlib" "C:\\Users\\scxgo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\liblibc-7dc5efd24952e919.rlib" "C:\\Users\\scxgo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\liballoc-b95120d391119ce4.rlib" "C:\\Users\\scxgo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\librustc_std_workspace_core-0e624f0b43962fb3.rlib" "C:\\Users\\scxgo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libcore-58985b8c03f907a8.rlib" "C:\\Users\\scxgo\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libcompiler_builtins-27c1b248396c205c.rlib" "advapi32.lib" "cfgmgr32.lib" "gdi32.lib" "kernel32.lib" "msimg32.lib" "opengl32.lib" "user32.lib" "winspool.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  = note: Non-UTF-8 output: 3dtile.3dtile.5vnerurs-cgu.4.rcgu.o : error LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 _osgb23dtile_path\xa3\xac\xb8\xc3\xb7\xfb\xba\xc5\xd4\xda\xba\xaf\xca\xfd __ZN97_$LT$core..iter..adapters..Map$LT$I$C$F$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4fold17h22f21e71ae03cce7E \xd6\xd0\xb1\xbb\xd2\xfd\xd3\xc3\r\n3dtile.3dtile.5vnerurs-cgu.4.rcgu.o : error LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 _degree2rad\xa3\xac\xb8\xc3\xb7\xfb\xba\xc5\xd4\xda\xba\xaf\xca\xfd __ZN7_3dtile4osgb18osgb_batch_convert17hf0510b9493dacc7dE \xd6\xd0\xb1\xbb\xd2\xfd\xd3\xc3\r\n3dtile.3dtile.5vnerurs-cgu.4.rcgu.o : error LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 _transform_c\xa3\xac\xb8\xc3\xb7\xfb\xba\xc5\xd4\xda\xba\xaf\xca\xfd __ZN7_3dtile4osgb18osgb_batch_convert17hf0510b9493dacc7dE \xd6\xd0\xb1\xbb\xd2\xfd\xd3\xc3\r\n3dtile.3dtile.5vnerurs-cgu.8.rcgu.o : error LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 _shp23dtile\xa3\xac\xb8\xc3\xb7\xfb\xba\xc5\xd4\xda\xba\xaf\xca\xfd __ZN7_3dtile5shape19shape_batch_convert17h38b872b628b4c24eE \xd6\xd0\xb1\xbb\xd2\xfd\xd3\xc3\r\n3dtile.3dtile.5vnerurs-cgu.9.rcgu.o : error LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 _make_gltf\xa3\xac\xb8\xc3\xb7\xfb\xba\xc5\xd4\xda\xba\xaf\xca\xfd __ZN7_3dtile4main17h674fd146f77756b7E \xd6\xd0\xb1\xbb\xd2\xfd\xd3\xc3\r\n3dtile.3dtile.5vnerurs-cgu.9.rcgu.o : error LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 _epsg_convert\xa3\xac\xb8\xc3\xb7\xfb\xba\xc5\xd4\xda\xba\xaf\xca\xfd __ZN7_3dtile4main17h674fd146f77756b7E \xd6\xd0\xb1\xbb\xd2\xfd\xd3\xc3\r\nD:\\git_projects\\3dtiles\\target\\release\\deps\\3dtile.exe : fatal error LNK1120: 6 \xb8\xf6\xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xc3\xfc\xc1\xee\r\n

error: aborting due to previous error

**Comment by fanvanzh** [comment]
看不出错误，请确认以下三点：
1、Windows x64 系统2、先安装VS2015 update3 、 C++， 在安装 rustup3、代码是 git clone 下载的，不是通过网页 点击 download 下载的

**Comment by fanvanzh** [comment]
看看是否是 rustup 工具链的问题。
详见问题 #122

**Comment by liyu998** [comment]
非常感谢，我试一下。











在 2020-01-08 15:58:27，"fanvanzh" <notifications@github.com> 写道：

看看是否是 rustup 工具链的问题。
详见问题 #122

**Comment by zhoulihe1981** [comment]
切换交叉工具链为msvc:
rustup toolchain install stable-x86_64-pc-windows-msvc
rustup default x86_64-pc-windows-msvc


https://github.com/rust-lang/rustup

**Comment by zhoulihe1981** [comment]
检查安装的工具链：
rustup check 
安装msvc交叉工具链：
rustup toolchain install stable-x86_64-pc-windows-msvc
设置msvc交叉工具链为默认：
rustup default stable-x86_64-pc-windows-msvc

**Comment by liangxiufeng** [comment]
非常感谢两位@zhoulihe1981 @liyu998，我这边也可以了
