### ISSUE TITLE
不支持KHR_technique_webgl

### ISSUE THREAD

**Issue by chaoslife** [fanvanzh/3dtiles#139]
请问哪个版本下载的extension数据不为KHR_technique_webgl，下载的首页预编译的为KHR_technique_webgl。
其它工具转出来为KHR_materials_unlit

**Comment by fanvanzh** [comment]
按理说不会啊，代码里都搜不到 KHR_technique_webgl 关键字。
是不是数据有缓存？

**Comment by chaoslife** [comment]
可能会是我的源osgb文件里带有这个了吗？我使用工具转为3dtiles后，里面的格式就为KHR_technique_webgl，现在我自己的工具单独去处理了一下这个格式，如果为KHR_materials_unlit就少一步处理了

**Comment by zwzhlj100000** [comment]
> 按理说不会啊，代码里都搜不到 KHR_technique_webgl 关键字。
> 是不是数据有缓存？

![image](https://user-images.githubusercontent.com/6670216/86074713-0e4f1000-bab9-11ea-91e9-47df83cdc38b.png)

**Comment by fanvanzh** [comment]
谢谢， 你标红的是 KHR_techniques_webgl。 注意是 techniques_webgl（多了个s）， techniques_webgl 是 Cesium 1.50 之后支持的标准。

**Comment by sunshineYPH** [comment]
KHR_techniques_webgl had been supported in commit[896a6ee] for Cesium1.50. But this field is draft that has not bring into gltf2.0. So the files b3dm and gltf converted from 3dtiles.exe were parsing failed in Cesium for unreal，three.js、babylon.

**Fix**
Replace field KHR_technique_webgl with  KHR_materials_unlit rather than KHR_techniques_webgl

**Reference doc**
https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_unlit
https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_unlit
https://www.cnblogs.com/cesium1/p/10062861.html

**Comment by fanvanzh** [comment]
KHR_techniques_webgl can render model by self-define shareder program.

If you don`t want this feature works, just switch to the PBR material.

https://github.com/fanvanzh/3dtiles/blob/7f0f8af86a0abc3cf915862c1ad81a79b5217b02/src/osgb23dtile.cpp#L888

**Comment by fanvanzh** [comment]
3dtile.exe -f osgb -i E:\osgb_path -o E:\out_path -c "{\"pbr\": true}"

**Comment by fanvanzh** [comment]
你的意思是用 KHR_materials_unlit 代替 KHR_technique_webgl 啊？

**Comment by fanvanzh** [comment]
fe04fb5ac99ceb4b76f732cceb3c9df434827cdf
KHR_materials_unlit 代替 KHR_technique_webgl

**Comment by FengFengmomo** [comment]
> 可能会是我的源osgb文件里带有这个了吗？使用的是大疆无人机的倾射文件
> 
> 我使用工具转为3dtiles后，里面的格式就为KHR_technique_webgl，现在我自己的工具单独去处理了一下这个格式，如果为KHR_materials_unlit就少一步处理了

请问你自己的工具处理完以后可以正常显示了吗？我也是用的大疆无人机生成的osgb文件。
