### ISSUE TITLE
Centos8.5 build失败了

### ISSUE THREAD

**Issue by howiewant** [fanvanzh/3dtiles#216]
`➜  3dtiles git:(linux_osg_370) ✗ cargo build --release
   Compiling _3dtile v0.1.0 (/root/3dtiles)
warning: field is never read: `version`
   --> src/main.rs:212:5
    |
212 |     pub version: String,
    |     ^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/root/3dtiles/target/release/deps/_3dtile-cb41946d99d80f4c._3dtile.057c38cd-cgu.0.rcgu.o" "/root/3dtiles/target/release/deps/_3dtile-cb41946d99d80f4c._3dtile.057c38cd-cgu.1.rcgu.o" "/root/3dtiles/target/release/deps/_3dtile-cb41946d99d80f4c._3dtile.057c38cd-cgu.10.rcgu.o" "/root/3dtiles/target/release/deps/_3dtile-cb41946d99d80f4c._3dtile.057c38cd-cgu.11.rcgu.o" "/root/3dtiles/target/release/deps/_3dtile-cb41946d99d80f4c._3dtile.057c38cd-cgu.12.rcgu.o" "/root/3dtiles/target/release/deps/_3dtile-cb41946d99d80f4c._3dtile.057c38cd-cgu.13.rcgu.o" "/root/3dtiles/target/release/deps/_3dtile-cb41946d99d80f4c._3dtile.057c38cd-cgu.14.rcgu.o" "/root/3dtiles/target/release/deps/_3dtile-cb41946d99d80f4c._3dtile.057c38cd-cgu.15.rcgu.o" "/root/3dtiles/target/release/deps/_3dtile-cb41946d99d80f4c._3dtile.057c38cd-cgu.2.rcgu.o" "/root/3dtiles/target/release/deps/_3dtile-cb41946d99d80f4c._3dtile.057c38cd-cgu.3.rcgu.o" "/root/3dtiles/target/release/deps/_3dtile-cb41946d99d80f4c._3dtile.057c38cd-cgu.4.rcgu.o" "/root/3dtiles/target/release/deps/_3dtile-cb41946d99d80f4c._3dtile.057c38cd-cgu.5.rcgu.o" "/root/3dtiles/target/release/deps/_3dtile-cb41946d99d80f4c._3dtile.057c38cd-cgu.6.rcgu.o" "/root/3dtiles/target/release/deps/_3dtile-cb41946d99d80f4c._3dtile.057c38cd-cgu.7.rcgu.o" "/root/3dtiles/target/release/deps/_3dtile-cb41946d99d80f4c._3dtile.057c38cd-cgu.8.rcgu.o" "/root/3dtiles/target/release/deps/_3dtile-cb41946d99d80f4c._3dtile.057c38cd-cgu.9.rcgu.o" "/root/3dtiles/target/release/deps/_3dtile-cb41946d99d80f4c.5gg36956iey2gyhs.rcgu.o" "-Wl,--as-needed" "-L" "/root/3dtiles/target/release/deps" "-L" "/root/3dtiles/target/release/build/_3dtile-32aa0fd3f1fe3a13/out" "-L" "./lib" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,--whole-archive" "-l_3dtile" "-Wl,--no-whole-archive" "-Wl,-Bdynamic" "-lstdc++" "-lOpenThreads" "-losg" "-losgDB" "-losgUtil" "-Wl,-Bstatic" "/root/3dtiles/target/release/deps/librayon-a8ae4e3fa8d73f85.rlib" "/root/3dtiles/target/release/deps/librayon_core-be00ad01e03a355f.rlib" "/root/3dtiles/target/release/deps/libnum_cpus-d8f16b2711e5d663.rlib" "/root/3dtiles/target/release/deps/libcrossbeam_deque-a58a0beae31f1cf3.rlib" "/root/3dtiles/target/release/deps/libcrossbeam_epoch-5bf93f4623a45dd5.rlib" "/root/3dtiles/target/release/deps/libmemoffset-14f343850be02c38.rlib" "/root/3dtiles/target/release/deps/libscopeguard-c857144e7f0e1819.rlib" "/root/3dtiles/target/release/deps/libcrossbeam_channel-b43372e4df0f6b9e.rlib" "/root/3dtiles/target/release/deps/libcrossbeam_utils-7da3bd51daea773a.rlib" "/root/3dtiles/target/release/deps/liblazy_static-0df5d4f37a836555.rlib" "/root/3dtiles/target/release/deps/libeither-9ac42eaf9ff48976.rlib" "/root/3dtiles/target/release/deps/libenv_logger-201290e301621095.rlib" "/root/3dtiles/target/release/deps/libregex-e5ba0de2b20728fb.rlib" "/root/3dtiles/target/release/deps/libaho_corasick-3040bb86979c8ab7.rlib" "/root/3dtiles/target/release/deps/libmemchr-06d76bcb96a352b9.rlib" "/root/3dtiles/target/release/deps/libregex_syntax-fbfd9647b67e68ae.rlib" "/root/3dtiles/target/release/deps/libhumantime-e0f716b26f3922fe.rlib" "/root/3dtiles/target/release/deps/libquick_error-0372981d47a58841.rlib" "/root/3dtiles/target/release/deps/libtermcolor-c1e591ee2a17ad46.rlib" "/root/3dtiles/target/release/deps/libchrono-2d44ced1ecbe194d.rlib" "/root/3dtiles/target/release/deps/libnum_integer-e29a57430a02535e.rlib" "/root/3dtiles/target/release/deps/libnum_traits-68fa78ce62b4eea2.rlib" "/root/3dtiles/target/release/deps/libtime-caee39f3a432b323.rlib" "/root/3dtiles/target/release/deps/libbyteorder-20fda3f2a9be6fa6.rlib" "/root/3dtiles/target/release/deps/libserde_xml_rs-d10b8e345ea62483.rlib" "/root/3dtiles/target/release/deps/liblog-a4fa134ef1d8d93a.rlib" "/root/3dtiles/target/release/deps/liblog-f8752b7be0ee0450.rlib" "/root/3dtiles/target/release/deps/libcfg_if-a04351a1e37ac403.rlib" "/root/3dtiles/target/release/deps/libxml-b2dc0e5ca3dede60.rlib" "/root/3dtiles/target/release/deps/libbitflags-bcf2f90df8bfb2b6.rlib" "/root/3dtiles/target/release/deps/libserde_json-cdf21e72795bf77b.rlib" "/root/3dtiles/target/release/deps/libryu-d593287be4da2cb5.rlib" "/root/3dtiles/target/release/deps/libitoa-2ec4667a79e65152.rlib" "/root/3dtiles/target/release/deps/libserde-0e60070beef3969c.rlib" "/root/3dtiles/target/release/deps/libclap-d93c382c4504f2a7.rlib" "/root/3dtiles/target/release/deps/libvec_map-5d3b872e0a1408b5.rlib" "/root/3dtiles/target/release/deps/libtextwrap-c273469f9debde5a.rlib" "/root/3dtiles/target/release/deps/libunicode_width-b88877dbb8531487.rlib" "/root/3dtiles/target/release/deps/libstrsim-65d231e2011670e5.rlib" "/root/3dtiles/target/release/deps/libbitflags-045e5e9961c5ccd8.rlib" "/root/3dtiles/target/release/deps/libatty-3f209c6220a01bda.rlib" "/root/3dtiles/target/release/deps/liblibc-9b4d7ce1f8684159.rlib" "/root/3dtiles/target/release/deps/libansi_term-594c980194a3606c.rlib" "-Wl,--start-group" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-7c582493123fc1dd.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-1392776590706175.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-2eb6edf4d031cd1e.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-33a7ad3b5f7fedf6.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-7d32adce541987d9.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-5cb369120f224726.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-6ab2efd1d2f431a9.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-567f611439253c7e.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-ebbc63efd6d2efc5.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-862830f0d224a2e1.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-cad0401ae7a80e32.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-fd54290077194763.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-4fc3313c8ccb1ec0.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-19bf8dffe82b09d4.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-afc95b1640c4beca.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-aff6658baa87e3d1.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-8be8a1689a4f7b48.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-5284934f66073844.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-2a0b2a4f96acb821.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/root/3dtiles/target/release/deps/_3dtile-cb41946d99d80f4c" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs"
  = note: /root/3dtiles/target/release/build/_3dtile-32aa0fd3f1fe3a13/out/lib_3dtile.a(osgb23dtile.o): In function `get_all_tree(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) [clone .localalias.1418]':
          osgb23dtile.cpp:(.text._Z12get_all_treeRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x2b1): undefined reference to `osgDB::readNodeFiles(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, osgDB::Options const*)'
          /root/3dtiles/target/release/build/_3dtile-32aa0fd3f1fe3a13/out/lib_3dtile.a(osgb23dtile.o): In function `osgb2glb_buf(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, MeshInfo&)':
          osgb23dtile.cpp:(.text._Z12osgb2glb_bufNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERS4_R8MeshInfo+0x134): undefined reference to `osgDB::readNodeFiles(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, osgDB::Options const*)'
          collect2: error: ld returned 1 exit status

  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

warning: `_3dtile` (bin "_3dtile") generated 1 warning
error: could not compile `_3dtile` due to previous error; 1 warning emitted`

**Comment by fanvanzh** [comment]
cargo build 之前设置下搜索路径呢？
export LD_LIBRARY_PATH=./lib

**Comment by maharogun** [comment]
i same err, too.
under ubuntu:20.04
apt install -y build-essential rustc cargo git libgl-dev
git clone https://github.com/fanvanzh/3dtiles.git
cd 3dtiles
git checkout linux_osg_370
export LD_LIBRARY_PATH=./lib     //or export LD_LIBRARY_PATH=/git/3dtiles/lib
cargo build --release
------------------------------------ omit  ----------------
note: /usr/bin/ld: /work/3dtiles/target/release/build/_3dtile-93803c7bf4da5814/out/lib_3dtile.a(osgb23dtile.o): in function `get_all_tree(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) [clone .localalias]':
          osgb23dtile.cpp:(.text._Z12get_all_treeRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x2cb): undefined reference to `osgDB::readNodeFiles(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, osgDB::Options const*)'
          /usr/bin/ld: /work/3dtiles/target/release/build/_3dtile-93803c7bf4da5814/out/lib_3dtile.a(osgb23dtile.o): in function `osgb2glb_buf(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, MeshInfo&)':
          osgb23dtile.cpp:(.text._Z12osgb2glb_bufNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERS4_R8MeshInfo+0x134): undefined reference to `osgDB::readNodeFiles(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, osgDB::Options const*)'
          collect2: error: ld returned 1 exit status
------------------------------------------------------------
What linux version did you run it on success?

**Comment by fanvanzh** [comment]
centos 7.3

**Comment by fanvanzh** [comment]
你自己用源码编译下 osg 试试

**Comment by maharogun** [comment]
> 你自己用源码编译下 osg 试试
thank you.
under ubuntu:20.04
i do pull "https://github.com/openscenegraph/OpenSceneGraph.git".
after build, paste lib-dir.  Cargo-build was successed.

**Comment by miurwoer** [comment]
我也是一样的错误欸，我的版本是 CentOS Linux release 7.9.2009 (Core)
以下是错误，大佬能不能指导一下：
[root@localhost 3dtiles_linux]# export LD_LIBRARY_PATH=./lib
[root@localhost 3dtiles_linux]# cargo build --release
   Compiling _3dtile v0.1.0 (/usr/local/soft/3dtiles_linux)
warning: field is never read: `version`
   --> src/main.rs:212:5
    |
212 |     pub version: String,
    |     ^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default
note: `ModelMetadata` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
   --> src/main.rs:210:10
    |
210 | #[derive(Debug, Deserialize)]
    |          ^^^^^
    = note: this warning originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)

error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/usr/local/soft/3dtiles_linux/target/release/deps/_3dtile-bde207ed7a937d3b._3dtile.53bddc0e-cgu.0.rcgu.o" "/usr/local/soft/3dtiles_linux/target/release/deps/_3dtile-bde207ed7a937d3b._3dtile.53bddc0e-cgu.1.rcgu.o" "/usr/local/soft/3dtiles_linux/target/release/deps/_3dtile-bde207ed7a937d3b._3dtile.53bddc0e-cgu.10.rcgu.o" "/usr/local/soft/3dtiles_linux/target/release/deps/_3dtile-bde207ed7a937d3b._3dtile.53bddc0e-cgu.11.rcgu.o" "/usr/local/soft/3dtiles_linux/target/release/deps/_3dtile-bde207ed7a937d3b._3dtile.53bddc0e-cgu.12.rcgu.o" "/usr/local/soft/3dtiles_linux/target/release/deps/_3dtile-bde207ed7a937d3b._3dtile.53bddc0e-cgu.13.rcgu.o" "/usr/local/soft/3dtiles_linux/target/release/deps/_3dtile-bde207ed7a937d3b._3dtile.53bddc0e-cgu.14.rcgu.o" "/usr/local/soft/3dtiles_linux/target/release/deps/_3dtile-bde207ed7a937d3b._3dtile.53bddc0e-cgu.15.rcgu.o" "/usr/local/soft/3dtiles_linux/target/release/deps/_3dtile-bde207ed7a937d3b._3dtile.53bddc0e-cgu.2.rcgu.o" "/usr/local/soft/3dtiles_linux/target/release/deps/_3dtile-bde207ed7a937d3b._3dtile.53bddc0e-cgu.3.rcgu.o" "/usr/local/soft/3dtiles_linux/target/release/deps/_3dtile-bde207ed7a937d3b._3dtile.53bddc0e-cgu.4.rcgu.o" "/usr/local/soft/3dtiles_linux/target/release/deps/_3dtile-bde207ed7a937d3b._3dtile.53bddc0e-cgu.5.rcgu.o" "/usr/local/soft/3dtiles_linux/target/release/deps/_3dtile-bde207ed7a937d3b._3dtile.53bddc0e-cgu.6.rcgu.o" "/usr/local/soft/3dtiles_linux/target/release/deps/_3dtile-bde207ed7a937d3b._3dtile.53bddc0e-cgu.7.rcgu.o" "/usr/local/soft/3dtiles_linux/target/release/deps/_3dtile-bde207ed7a937d3b._3dtile.53bddc0e-cgu.8.rcgu.o" "/usr/local/soft/3dtiles_linux/target/release/deps/_3dtile-bde207ed7a937d3b._3dtile.53bddc0e-cgu.9.rcgu.o" "/usr/local/soft/3dtiles_linux/target/release/deps/_3dtile-bde207ed7a937d3b.1z7fatrocflcdeum.rcgu.o" "-Wl,--as-needed" "-L" "/usr/local/soft/3dtiles_linux/target/release/deps" "-L" "/usr/local/soft/3dtiles_linux/target/release/build/_3dtile-11009c51e5589f01/out" "-L" "./lib" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-l_3dtile" "-Wl,-Bdynamic" "-lstdc++" "-lOpenThreads" "-losg" "-losgDB" "-losgUtil" "-Wl,-Bstatic" "/usr/local/soft/3dtiles_linux/target/release/deps/librayon-3141a071051be292.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/librayon_core-91bc8fdc5f5057aa.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libnum_cpus-3ac2a802caedcbd6.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libcrossbeam_deque-bacc66c430d50d8e.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libcrossbeam_epoch-4dfef87d51875ea0.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libmemoffset-213003319e8a6081.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libscopeguard-cc20f1d9e660717a.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libcrossbeam_channel-ec6f7fbdaf54cc94.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libcrossbeam_utils-ae65609fcfd2701f.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/liblazy_static-7afcd8eab5501c1b.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libeither-7335581cdff27c32.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libenv_logger-7a0f8da55ebd108d.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libregex-1f3e9518c1a4bfc9.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libaho_corasick-cf72442e04b19736.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libmemchr-6732bea9ab1b270b.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libregex_syntax-485812582e0f94a9.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libhumantime-642338a91049065c.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libquick_error-5ebd50f4c640c617.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libtermcolor-7ee3c4b4d0011116.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libchrono-bb3a7c45dcda3866.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libnum_integer-65fe104b9de00f97.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libnum_traits-ddb6237401d108d6.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libtime-db1ec37ec8d3c90a.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libbyteorder-a3fe6a063f2447da.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libserde_xml_rs-a512fb3af8f1a5a6.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/liblog-2b6046f65eb3f59f.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/liblog-cdaf5aec6648d751.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libcfg_if-d2f5240c3ba9f1eb.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libxml-741dc519417eac24.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libbitflags-43049f2d05493925.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libserde_json-141c25cf358cceea.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libryu-4cc6b82a4c5ec990.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libitoa-107e6377c9cd2077.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libserde-404a6b8dd6125031.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libclap-93ee464844a31270.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libvec_map-d4fa35327a0e8d0d.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libtextwrap-bb7e8f777a0a70af.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libunicode_width-c3838d3852bc6d26.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libstrsim-17d78722065bea08.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libbitflags-5f35ade335c71dac.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libatty-e6be80b5bd827720.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/liblibc-ee57dae12a73009e.rlib" "/usr/local/soft/3dtiles_linux/target/release/deps/libansi_term-40c6a20a0a9d991e.rlib" "-Wl,--start-group" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-05b39ac0cb4c5688.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-ccaa149b737d6503.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-a94a6388c153126b.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-1ecfa264246b85c6.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-ee710154a50440b8.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-f09986d873ea8592.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-f3521e20c99619ab.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-df6036c77d75ce21.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-24f91c1a1dfc7e13.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-bffcc61991adb202.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-cf22313353d8663e.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-c45fb100f99430e9.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-0cdc47a8a81950ea.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-f1e158606c4c82f6.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-0b608b5ef4df0ec4.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-b8438dc0bcbbcc08.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-70e2ae036775ff2f.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-815d281f7068a893.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-377835cfab8dae0d.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/usr/local/soft/3dtiles_linux/target/release/deps/_3dtile-bde207ed7a937d3b" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-Wl,-O1" "-nodefaultlibs"
  = note: /usr/bin/ld:./lib/libOpenThreads.so: file format not recognized; treating as linker script
          /usr/bin/ld:./lib/libOpenThreads.so:1: syntax error
          collect2: error: ld returned 1 exit status
          

warning: `_3dtile` (bin "_3dtile") generated 1 warning
error: could not compile `_3dtile` due to previous error; 1 warning emitted

**Comment by fanvanzh** [comment]
增加了 linux 版本的编译测试

**Comment by fanvanzh** [comment]
增加了 linux 版本的编译测试
